### ISSUE TITLE
kids customs code with Python tool could be much easier

### ISSUE THREAD

**Issue by ptal78** [rafaelaroca/BIPES_ui_testing#31]
It would be of great benefit to younger kids using Bipes custom Python code to use the **Pin** function instead of the **machine.Pin** function.

To do this, can you please change the code in the set pin block and importantly it won't upset any of your other pin functions that use gpio_set, and your Read Pin block is already using this **from machine import Pin** anyway. So it would be consistent to change the Set Pin block to match it also.

**from this:**

```
import machine

def gpio_set(pin,value):
  if value >= 1:
    machine.Pin(pin, machine.Pin.OUT).on()
  else:
    machine.Pin(pin, machine.Pin.OUT).off()
```

**to this:**

```
from machine import Pin

def gpio_set(pin,value):
  if value >= 1:
    Pin(pin, Pin.OUT).on()
  else:
    Pin(pin, Pin.OUT).off()
```
nothing else needs to change here. And with this one change, custom Python blocks will be easier, as the kids can initialise the pins with the set pin block, and have access to using the **Pin** function instead of the **machine.Pin** function

**Comment by JorgeGMarques** [comment]
Hello,

I changed `machine.Pin`, `machine.PWM` and `machine.ADC` to `Pin`, `PWM` and `ADC` with commit e76177c.

The `Blockly,Python.definitions_` are `import_pin`, `import_pwm` and `import_adc`.

P.S. Since the auto-generated `micropython` toolbox is problematic, I kept with the full class extension.

Best regards,
