### ISSUE TITLE
Bug - logic 'if' block failing to add 'else if', or 'else' extensions to the block

### ISSUE THREAD

**Issue by ptal78** [rafaelaroca/BIPES_ui_testing#36]
Doing this:

![image](https://user-images.githubusercontent.com/24988399/127253893-1a62adb1-b663-4c17-bb1e-8df5665404ae.png)

Would make you think it will extend the block to add the else if extension, and the else extension to the if block, but it doesn't.

This was tested using the ESP32.

**Comment by rafaelaroca** [comment]
Hello. This works perfectly for me. Just tested on ESP32.

![image](https://user-images.githubusercontent.com/31751413/127346341-485ba100-0835-4296-b69c-26deb460e839.png)

![image](https://user-images.githubusercontent.com/31751413/127346453-58fcc3b9-a748-4adf-8a7e-ecf55eca1589.png)

Could you give more details? It really works correctly to me.

**Comment by JorgeGMarques** [comment]
Sometimes this bug happens to me, but I couldn't figure out whats is triggering [Mutators](https://developers.google.com/blockly/guides/create-custom-blocks/extensions) to stop working.

My guess is some `.setTimeout` not resolving and bricking the mutators.

**Comment by rafaelaroca** [comment]
Wow. Never happened to me. Curious to know more about it...using Google Chrome?

**Comment by ptal78** [comment]
It's working now. Yes, Google Chrome.

What web browser and version do you use for testing?

**Comment by JorgeGMarques** [comment]
We use Firefox > 90 and Chrome > 93.

We made some big code refactoring in the last week, unifying the code between `beta2` and `beta2serial` and improving many modules, the platform should be more stable now.
For example, the terminal now works with touchscreens, the Files tab fail way less when fetching, listing and writing files (just still need some styling).

Anyway, if the bug seems to be completely resolved, please close the issue.
