### ISSUE TITLE
Android keyboard opens then immediately closes when input field is selected

### ISSUE THREAD

**Issue by casjengu** [rafaelaroca/BIPES_ui_testing#5]
Hello,

I'm currently watching this project as I might want to use it to help kids / students learn how to program a Wemos D1 mini using Micropython.

While testing the interface, I noticed a problem with Android devices. When I click on an input field (e.g. the 'Address' and the 'Password' field in the 'Console' tab) that opens the Android keyboard, the keyboard closes again immediately. I tested this with a Samsung Galaxy A50 and a Samsung Galaxy S8. I used the Chrome browser and the integrated Samsung browser. I also activated the desktop mode for testing. It worked with an Apple iPad.  My guess is that opening the Android keyboard triggers your resize EventListener, but I don't really have much experience with web programming..
Are only devices with a certain minimum resolution supported?

Anyway, keep up the great work. This project looks very promising!

**Comment by JorgeGMarques** [comment]
Hello!

The bug was resolved by merging the current `google/blockly` library files into master.

Our `Makefile`  already kept these updated with the commands `git-clone` and `copy`, but since the older version was the origin of the issue, I merged into master (our server has not yet been updated).

> Are only devices with a certain minimum resolution supported?

The main issue with smaller screens is making the Blocks tab fit, if we can figure out a UI for Blockly that works for these devices I reckon the rest of the tabs could be easily adapted.

Best regards
